name: Run Playwright tests and eslint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run playwright tests
        run: |
          npm install
          npm run test

      - name: run eslint
        run: |
          npm install
          npm run lint

      - name: run svelte kit check
        run: |
          npm install
          npm run check
